name: CI & Update Infra

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout Code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Go (Good practice to run tests first)
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      
      # - name: Run Tests
      #   run: go test ./...

      # 3. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build and Push Docker Image
      # We use the short git commit SHA as the tag for uniqueness
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: flaminglassoo1996/auth-service:${{ github.sha }}

      # 5. Update Infra Repository
      - name: Update Infra Manifest
        env:
          GH_TOKEN: ${{ secrets.INFRA_REPO_PAT }}
          NEW_TAG: ${{ github.sha }}
        run: |
          # Configure Git
          git config --global user.email "flaminglassoo@gmail.com"
          git config --global user.name "Arief Zainuri"
          
          # Clone the Infra Repo
          git clone https://$GH_TOKEN@github.com/ariefzainuri96/go-api-ecommerce-infra.git
          cd go-api-ecommerce-infra
          
          # Use yq to update the specific image tag in docker-compose.yaml
          # This assumes yq is installed (it is on standard GitHub runners) or use a portable binary
          # The logic: Find the service 'auth-service', update its 'image' field
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq
          
          yq -i ".services.auth-service.image = \"flaminglassoo1996/auth-service:$NEW_TAG\"" docker-compose.yaml
          
          # Commit and Push
          git add docker-compose.yaml
          git commit -m "Update auth-service image to $NEW_TAG"
          git push origin master